# Development Build Profile for OpenCog
# This profile includes all components with debug symbols and tests

# Define component-specific build options
$COMPONENT_CONFIG = @{}

# Development configuration for each component
$COMPONENT_CONFIG["cogutil"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["atomspace"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["unify"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["ure"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["atomspace-storage"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["atomspace-rocks"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["atomspace-pgres"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["cogserver"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_NETWORK_SERVER=ON"
$COMPONENT_CONFIG["attention"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["spacetime"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["pln"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["lg-atomese"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["learn"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"
$COMPONENT_CONFIG["opencog"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_LEARNING=ON -DENABLE_PLN=ON -DENABLE_ATTENTION=ON"
$COMPONENT_CONFIG["sensory"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_VISION=ON -DENABLE_AUDIO=ON"
$COMPONENT_CONFIG["evidence"] = "-DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug"

# No components to skip in development build
$SKIP_COMPONENTS = @()

Write-Output "Development build profile loaded."
Write-Output "This profile includes all components with debug symbols and tests." 