
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "atomspace"
version = "5.1.0"
authors = [
  { name="OpenCog Development", email="opencog@googlegroups.com" },
]
description = "The AtomSpace Hypergraph Database"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Linux",
]
license = "AGPL"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/opencog/atomspace"
Issues = "https://github.com/opencog/atomspace/issues"
